import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Printer } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge, riskTone } from "@/components/ui/Badge";
import { Skeleton } from "@/components/ui/Skeleton";
import { CircularScore } from "@/components/compliance/CircularScore";
import { ChecklistItem } from "@/components/compliance/ChecklistItem";
import { MismatchCard } from "@/components/compliance/MismatchCard";
import { api } from "@/lib/api";
import { formatDate, formatDateTime } from "@/lib/utils";
import { Bid, Bidder, Tender } from "@/types";

export default function ReportDetail() {
  const { id } = useParams();
  const [data, setData] = useState<{ generatedAt: string; bid: Bid; summary: any } | null>(null);

  useEffect(() => { api.get<{ generatedAt: string; bid: Bid; summary: any }>(`/reports/${id}`).then(setData); }, [id]);

  if (!data) return <AppShell breadcrumb={[{ label: "Reports", to: "/reports" }, { label: "..." }]}><Skeleton className="h-96" /></AppShell>;

  const { bid, generatedAt } = data;
  const bidder = typeof bid.bidderId === "object" ? (bid.bidderId as Bidder) : null;
  const tender = typeof bid.tenderId === "object" ? (bid.tenderId as Tender) : null;

  return (
    <AppShell breadcrumb={[{ label: "Reports", to: "/reports" }, { label: bid.bidRefId }]}>
      <div className="mb-5 flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h1 className="text-xl font-bold text-ink-900">Compliance Report — {bid.bidRefId}</h1>
          <p className="mt-0.5 text-sm text-ink-500">Generated {formatDateTime(generatedAt)}</p>
        </div>
        <Button variant="outline" onClick={() => window.print()}><Printer size={15} /> Print / Save PDF</Button>
      </div>

      <div className="space-y-5">
        <Card>
          <CardContent className="grid grid-cols-1 gap-6 py-6 sm:grid-cols-3">
            <div>
              <p className="text-xs text-ink-500">Bidder</p>
              <p className="text-lg font-bold text-ink-900">{bidder?.companyName}</p>
              <p className="mt-2 text-xs text-ink-500">Tender</p>
              <p className="text-sm text-ink-700">{tender?.name}</p>
              <p className="mt-2 text-xs text-ink-500">Submitted</p>
              <p className="text-sm text-ink-700">{formatDate(bid.submittedAt)}</p>
            </div>
            <div className="flex justify-center"><CircularScore score={bid.complianceScore} recommendation={bid.recommendation} size={140} /></div>
            <div className="text-sm sm:text-right">
              <p className="text-xs text-ink-500">Risk Level</p>
              <Badge tone={riskTone(bid.riskLevel)} className="text-sm">{bid.riskLevel} ({bid.riskScore}/100)</Badge>
              <p className="mt-2 text-xs text-ink-500">Decision</p>
              <p className="font-semibold text-ink-900">{bid.decision ? bid.decision.outcome.replace(/_/g, " ") : "Pending Officer Review"}</p>
              {bid.decision && <p className="mt-1 max-w-xs text-xs text-ink-500 sm:ml-auto">"{bid.decision.remarks}"</p>}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader><CardTitle>Requirement-Wise Breakdown</CardTitle></CardHeader>
          <CardContent className="space-y-2.5">
            {bid.requirementResults.map((r) => <ChecklistItem key={r.key} result={r} />)}
          </CardContent>
        </Card>

        {bid.mismatches.length > 0 && (
          <Card>
            <CardHeader><CardTitle>Mismatches & Exceptions</CardTitle></CardHeader>
            <CardContent className="space-y-3">
              {bid.mismatches.map((m, i) => <MismatchCard key={i} mismatch={m} />)}
            </CardContent>
          </Card>
        )}

        <p className="text-center text-xs text-ink-300 print:mt-8">
          This report is generated by ComplyGeM's rule-based compliance engine and is intended as decision support only.
          The final procurement decision rests with the reviewing officer.
        </p>
      </div>
    </AppShell>
  );
}
